server:
  app_name: My Geek Time
  run_mode: debug
  http_addr: 0.0.0.0
  http_port: 8090
jwt:
  secret: mygeektime-secret
  expires: 86400
database:
# driver: mysql
# source: root:123456@tcp(127.0.0.1:3306)/mygeektime?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
# driver: postgres
# source: host=127.0.0.1 user=postgres password=123456 dbname=mygeektime port=5432 sslmode=disable TimeZone=Asia/Shanghai
  driver:  sqlite   # mysql|postgres|sqlite
  source:  mygeektime.db
  max_idle_conns: 10
  max_open_conns: 10
storage: # mp4 or mp3 save folder
  driver: local
  directory: /tmp/repo  # Customize download folder, default to execute repo directory under the directory
  bucket: object
  host: http://127.0.0.1:8090  # Keep the port consistent with the http_port in the server
browser:
  driver_path: chromedriver # If there is no cookie file, chromedriver will be used by default to simulate login and obtain cookies
  cookie_path: cookie.txt  # Geektime's cookie file storage location
  open_browser: true # Automatically open browser after service startup
geektime:
  auto_sync: true # Automatically sync geektime api data to db
  auth_validate: true  # check geektime account auth
