server:
  app_name: My Geek Time
  run_mode: debug
  http_addr: 0.0.0.0
  http_port: 8090
jwt:
  secret: mygeektime-secret
  expires: 86400
redis:
  addr: 127.0.0.1:6379
  password: 123456
  pool_size: 20
  max_open_conns: 10
database:
  driver:  sqlite   # mysql|postgres|sqlite
  source:  mygeektime.db
  # source: root:123456@tcp(127.0.0.1:3306)/mygeektime?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
  # source: host=127.0.0.1 user=postgres password=postgres dbname=mygeektime port=5432 sslmode=disable TimeZone=Asia/Shanghai
  max_idle_conns: 10
  max_open_conns: 10
email:
  host: smtp.qq.com
  port: 587
  from:
  user:
  password:
storage: # mp4 or mp3 save folder
  driver: local
  directory: repo  # Customize download folder, default to execute repo directory under the directory
  bucket: object
  host: http://127.0.0.1:8090  # Keep the port consistent with the http_port in the server
browser:
  open_browser: true # Automatically open browser after service startup
