server:
  app_name: My Geek Time
  run_mode: debug
  http_addr: 0.0.0.0
  http_port: 8090
jwt:
  secret: mygeektime-secret
  expires: 7200
database:
  driver: mysql
  source: root:123456@tcp(127.0.0.1:3306)/mygeektime?charset=utf8&parseTime=True&loc=Local&timeout=1000ms
  # driver: sqlite   # mysql|postgres|sqlite
  # source:  mygeektime.db
  max_idle_conns: 10
  max_open_conns: 10
storage: # mp4 or mp3 save folder
  driver: local
  source: /tmp/repo
browser:
  driver_path: ./chromedriver
  cookie_path: ./cookie.txt
  open_browser: true
geektime:
  auto_sync: true # auto sync geektime api data to db
