version: "3"
networks:
  mygeektime:
    driver: bridge
services:
  mysql:
    image: mysql:latest
    hostname: "mysql"
    restart: always
    networks:
      - mygeektime
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=mygeektime
    volumes:
      - ./mysql/data:/var/libs/mysql
      - ./mysql/init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/init/sys_dicts.sql:/docker-entrypoint-initdb.d/sys_dicts.sql
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "33060:3306"
  server:
    hostname: mygeektime
    # build: ../         # build  from local dockerfile
    image: zkep/mygeektime:latest
    platform: linux/amd64  # linux/arm64 指定架构平台
    privileged: true
    restart: always
    networks:
      - mygeektime
    command: server --config=config.yml
    ports:
      - "8090:8090"
    environment:
      - GIN_MODE=test
    volumes:
      -  ./server/repo:/repo
      -  ./server/config.yml:/config.yml
    depends_on:
      - mysql