name: mygeektime
networks:
  mygeektime:
    driver: bridge
services:
  mysql:
    image: mysql:latest
    hostname: "mysql"
    restart: always
    networks:
      - mygeektime
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=mygeektime
    volumes:
      - ./mysql/data:/var/libs/mysql
      - ./mysql/init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql/init/tasks.sql:/docker-entrypoint-initdb.d/tasks.sql
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 33060:3306
  server:
    hostname: mygeektime
    build: ../                       # build  from local dockerfile
    # image: zkep/mygeektime:latest    # other os
    image: zkep/mygeektime:mac-m    # macos arm64
    privileged: true
    restart: always
    networks:
      - mygeektime
    command: server --config=config.yml
    ports:
      - 8090:8090
    environment:
      - GIN_MODE=test
    volumes:
      -  ./server/repo:/repo
      -  ./server/config.yml:/config.yml
    depends_on:
      - mysql